### ISSUE TITLE
Adaptar método run para lidar com o algoritmo de ordenação

### ISSUE THREAD

**Issue by Dev-GabCosta** [mdantasvilelazup/AlgorithmTester#1]
@mdantasvilelazup Não entendo porque mesmo tendo implementado a interface Algorithm e mesmo com a ordenação estando correta o array continua desordenado. Por favor, tente verificar isso. Na função main, os trechos referentes à classe Sum foram removidos ou comentados para testar a ordenação.

**Comment by mdantasvilelazup** [comment]
Resolvido com a branch test-update
